on: [push]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  package:
    runs-on: ubuntu-latest
    container:
      image: wonderlandengine/editor:latest
    steps:
      - name: Install Git
        run: apt-get update && apt-get install -y git git-lfs
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Package
        run: /usr/local/bin/entrypoint.sh WonderlandEditor --windowless --package --project vrps.wlp --output ./public/
        env:
          WLE_CREDENTIALS: ${{ secrets.WLE_CREDENTIALS }}

      - name: Gzip
        run: find ./public/ -type f ! -name '*.gz' -exec gzip -k "{}" \;

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy-pages:
    needs: package
    runs-on: ubuntu-latest
    if: ${{ format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
